### ISSUE TITLE
Ingame Scroll View

### ISSUE THREAD

**Issue by michaelheiml** [Sacred-Seed-Studio/Unity-File-Debug#6]
Nice asset - what do you think about the option to write the output to an ingame scroll view rather than a file?

I work on a remote Android device where it would be much easier to see exceptions etc. directly on screen rather than connecting + browsing through the file system.

**Comment by Frozenfire92** [comment]
Hi Michael,

thanks for the feedback! I think this should be quite easy to do, I'm thinking the Unity File Debug prefab will get a reference to a UI Text component. If set it will append the output. Is this something like you were thinking?

**Comment by michaelheiml** [comment]
Sounds good, maybe use a scroll view text rather than just a text component for a better overview/scrolling with a lot of Debug output.

**Comment by Frozenfire92** [comment]
After investigating this I think its outside of the scope of this repository. It can be very quick that a Scroll Rect / UI Text component fills up with logs and will start to error out like so

```
ArgumentException: Mesh can not have more than 65000 vertices
UnityEngine.UI.VertexHelper.FillMesh
```

and 

```
String too long for TextMeshGenerator. Cutting off characters.
UnityEngine.Canvas:SendWillRenderCanvases()
```

A proper solution I would expect needs something like occlusion culling. One of the goals of this repository is to be small, and easy to understand and hack yourself. I think adding something like this in is only going to complicate things for most users. I will paste the code I did in an experiment incase you want to do this yourself (it was using Text on a Scroll Rect)

```c#
// UnityFileDebug/Lib/Logger/Scripts/UnityFileDebug.cs
using UnityEngine.UI;
...
public Text uiTextOutput;
...
Application.logMessageReceived += HandleLog;

if (uiTextOutput != null)
{
    uiTextOutput.text = "";
    Application.logMessageReceived += OutputLogToText;
}
...
void OutputLogToText(string logString, string stackTrack, LogType type)
{
    uiTextOutput.text += logString;
}
```

```c#
// UnityFileDebug/Lib/Logger/Editor/UnityFileDebugEditor.cs
...
SerializedProperty uiTextOutput;
GUIContent uiTextOutputContent;
...
uiTextOutputContent = new GUIContent
{
    text = "UI Text Output",
    tooltip = "Unity UI Text component"
};
...
uiTextOutput = serializedObject.FindProperty("uiTextOutput");
...
EditorGUILayout.PropertyField(uiTextOutput, uiTextOutputContent);
```

**Comment by Frozenfire92** [comment]
This may be relevant/help in displaying large amounts of logs https://bitbucket.org/Unity-Technologies/list-view-framework

**Comment by Frozenfire92** [comment]
also check out https://github.com/bbbscarter/UberLogger
